# Generated by Django 4.2.5 on 2023-09-27 03:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_avatar_link_alter_post_hashtags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Chuyên mục', 'verbose_name_plural': 'Chuyên mục'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Trạng thái xóa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Trạng thái xóa'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deteted',
            field=models.BooleanField(default=False, verbose_name='Đã xóa'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Bài viết'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bookmark'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bookmark'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên chuyên mục'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Đã chỉnh sửa'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.comment', verbose_name='Bình luận cha'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Bài viết'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='achievement',
            field=models.IntegerField(choices=[(5, 'Kim cương'), (4, 'Bạch kim'), (3, 'Vàng'), (2, 'Bạc'), (1, 'Đồng'), (0, 'Chưa có thành tích')], default=0, verbose_name='Thành tích'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_link',
            field=models.CharField(default='/static/user_layout/images/default-avatar.jpg', max_length=1024, verbose_name='Link ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='count_violated',
            field=models.IntegerField(default=0, verbose_name='Số lần vi phạm'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=10, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_banned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bị cấm'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL, verbose_name='Người được theo dõi'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Người theo dõi'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian theo dõi'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên hashtag'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhận'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='app.category', verbose_name='Chuyên mục'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='app.hashtag', verbose_name='Hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0, verbose_name='Chế độ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Normal'), (2, 'Deleted'), (3, 'Banned'), (4, 'Waiting for approval'), (5, 'Rejected')], default=0, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Bài viết'),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thanh toán'),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người thanh toán'),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='feedback_value',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Bài viết'),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian vote'),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người Vote'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='is_resolved',
            field=models.BooleanField(choices=[(True, 'Resolved'), (False, 'Not resolved')], default=False, verbose_name='Trạng thái giải quyết'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reason',
            field=models.CharField(max_length=1024, verbose_name='Lý do'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reported_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_post', to='app.post', verbose_name='Bài viết bị báo cáo'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_post', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian báo cáo'),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='is_resolved',
            field=models.BooleanField(choices=[(True, 'Resolved'), (False, 'Not resolved')], default=False, verbose_name='Trạng thái giải quyết'),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='reason',
            field=models.CharField(max_length=1024, verbose_name='Lý do'),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL, verbose_name='Người bị báo cáo'),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo'),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian báo cáo'),
        ),
    ]
