# Generated by Django 4.2.5 on 2023-10-02 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_category_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='receive_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notify',
            field=models.IntegerField(choices=[(0, 'Like_post'), (1, 'Comment'), (2, 'Reply_comment')], default=-1, verbose_name='Loại thông báo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(help_text='Nội dung thông báo chứa id post hoặc id comment hoặc id reply comment', max_length=1000, verbose_name='Nội dung'),
        ),
    ]
